version: '3.0'
services:
  mymongodb:
    container_name: mymongodb
    build:
      context: .
      dockerfile: Dockerfile-mongo
    image: mongodb:1.0.0
    ports:
      - "27017:27017"
    volumes:
    - ./mongovol:/data/db
    restart: always

  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:1.0.0
    ports:
      - "8111:8111"
    links:
      - mymongodb:mymongodb
